# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serial',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
