# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_post_serial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Course_Post',
        ),
    ]
