# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0003_auto_20190311_2035'),
        ('blogproject', '0003_category_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('belong', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogproject.Post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('belong', models.PositiveIntegerField(default=0)),
                ('coursePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course_Post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('powerDelete', models.BooleanField(default=True)),
                ('powerChange', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='commentcourse',
            name='users',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='comments.CommentUsers'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='comments.CommentUsers'),
        ),
    ]
