# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentusers_lasttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentusers',
            name='userIp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
