# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentusers_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcourse',
            name='Native',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
