# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20190328_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimg',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseimg',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
