# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogproject', '0002_auto_20190228_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
